[[main]]
  name = "Categories"
  identifier = "categories"
  weight = 20
  url = "en/categories"
  pre = '<i class="fas fa-fw fa-folder me-1"></i>'

[[main]]
  name = "Tags"
  identifier = "tags"
  weight = 30
  url = "en/tags"
  pre = '<i class="fas fa-fw fa-tags me-1"></i>'

[[main]]
  name = "Series"
  identifier = "series"
  weight = 40
  url = "en/series"
  pre = '<i class="fas fa-fw fa-columns me-1"></i>'

[[main]]
  name = "Projects"
  identifier = "projects"
  weight = 100
[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
[[main]]
  parent = "projects"
  name = "GOPKGS"
  url = "https://gopkgs.net/"
[[main]]
  parent = "projects"
  name = "Yii 2 Admin"
  url = "https://admin.yii2.razonyang.com/"
[[main]]
  parent = "projects"
  name = "Hugo Bootstrap Theme"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
